name: mp3_player
description: A simple MP3 player with playlist functionality
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_selector: ^1.0.3
  audio_metadata_reader: ^1.4.1
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.1.6
  http: ^1.1.0
  id3_codec: ^1.0.0
  audio_session: ^0.1.18
  permission_handler: ^11.3.0
  miniplayer: ^1.0.1
  provider: ^6.1.1
  file_picker: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
